name: Build Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Plugin
        run: |
          cd ..
          cd ..
          xcodebuild -project HermesVoiceEQ/Builds/MacOSX/HermesVoiceEQ.xcodeproj -scheme HermesVoiceEQ -configuration Release build

      # Add additional steps for testing, packaging, etc. as needed
