name: Build Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Xcode
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Save Projucer Project
        run: |
          Projucer/Projucer.app/Contents/MacOS/Projucer --resave HermesVoiceEQ/"Hermes Voice EQ.jucer"

      - name: Build Plugin Mac AU & VST3
        run: |
          cd HermesVoiceEQ/Builds/MacOSX
          xcodebuild -project "Hermes Voice EQ.xcodeproj" -scheme "Hermes Voice EQ - All" -configuration Release

      - name: Download Pluginval
        run: |
          cd Pluginval
          curl -L "https://github.com/Tracktion/pluginval/releases/latest/download/pluginval_macOS.zip" -o pluginval.zip
          unzip pluginval
        
      - name: Validate Mac AU
        run: |
          Pluginval/pluginval.app/Contents/MacOS/pluginval --strictness-level 5 --validate-in-process --verbose --validate HermesVoiceEQ/Builds/MacOSX/build/Release/Hermes\ Voice\ EQ.component

      - name: Delete .a files
        run: rm -R HermesVoiceEQ/Builds/MacOSX/build/Release/libHermes\ Voice\ EQ.a

      - name: Upload Mac Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Mac-Hermes-Voice-EQ-Artifacts
          path: HermesVoiceEQ/Builds/MacOSX/build/Release