name: Build Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Xcode
        uses: actions/setup-node@v2
        with:
          node-version: '14'

#      - name: Build Projucer
#        run: |
#          cd modules/JUCE/extras/Projucer/Builds/MacOSX
#          xcodebuild -project Projucer.xcodeproj -scheme "Projucer - App" -configuration Release
#          cp -R build/Release/Projucer.app builds/ 

      - name: Save Projucer Project
        run: |
          cd Projucer
#          Projucer.app/Contents/MacOS/Projucer --resave HermesVoiceEQ/"Hermes Voice EQ.jucer"

#      - name: Build Plugin Mac AU
#        run: |
#          cd HermesVoiceEQ/Builds/MacOSX
#          xcodebuild -project "Hermes Voice EQ.xcodeproj" -scheme "Hermes Voice EQ - AU" -configuration Release
#          cp -R build/Release/"Hermes Voice EQ.component"