name: Build Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Xcode
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Save Projucer Project
        run: |
          Projucer/Projucer.app/Contents/MacOS/Projucer --resave HermesVoiceEQ/"Hermes Voice EQ.jucer"

      - name: Build Plugin Mac AU & VST3
        run: |
          cd HermesVoiceEQ/Builds/MacOSX
          xcodebuild -project "Hermes Voice EQ.xcodeproj" -scheme "Hermes Voice EQ - All" -configuration Release

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Hermes-Voice-EQ-Artifacts
          path: HermesVoiceEQ/Builds/MacOSX/build/Release/
        