name: Build Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Xcode
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Create JUCE folder
        run: |
            # Create the JUCE folder
            mkdir -p modules/juce
  
      - name: Install JUCE and Projucer
        run: |
            # Download and install JUCE
            curl -L "https://github.com/juce-framework/JUCE/archive/refs/tags/6.0.8.tar.gz" -o juce.tar.gz
            tar -xzvf juce.tar.gz
            rm juce.tar.gz
            mv JUCE-6.0.8 modules/juce
  
            # Download and install Projucer
            curl -L "https://github.com/juce-framework/JUCE/releases/download/6.0.8/projucer-macOS" -o projucer
            chmod +x projucer
            mv projucer modules/juce

      # Add additional steps for testing, packaging, etc. as needed
