name: Build Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build Plugin
        run: |
          xcodebuild -project "HermesVoiceEQ/Builds/MacOSX/HermesVoiceEQ.xcodeproj" -scheme "Hermes-Voice-EQ-AU-Release" -configuration Release build

      # Add additional steps for testing, packaging, etc. as needed