name: Build Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Xcode
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build Projucer
        run: |
          cd modules/JUCE/extras/Projucer/Builds/MacOSX
          xcodebuild -project Projucer.xcodeproj -scheme "Projucer - App" -configuration Release
          cp -R build/Release/Projucer.app builds/ 

      - name: Test Projucer
        run: |
          modules/JUCE/extras/Projucer/Builds/MacOSX/build/Release/Projucer.app/Contents/MacOS/Projucer --status HermesVoiceEQ/"Hermes Voice EQ.jucer"

#          /Hermes Voice EQ.jucer
#           Name: Hermes Voice EQ
  #         UID: aU7yt3
    #       Modules:
      #       juce_audio_basics
        #     juce_audio_devices
          #   juce_audio_formats
            # juce_audio_plugin_client
            # juce_audio_processors
            # juce_audio_utils
            # juce_core
            # juce_data_structures
            # juce_dsp
            # juce_events
            # juce_graphics
            # juce_gui_basics
            # juce_gui_extra
            # viator_modules
