name: Build Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Xcode
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Create JUCE folder
        run: |
            # Create the JUCE folder
            mkdir -p modules/juce
  
      - name: Install JUCE and Projucer
        run: |
            # Download and install JUCE
            cd modules/juce
            git clone https://github.com/juce-framework/JUCE.git
      
      - name: Build Projucer
        run: |
          cd modules/juce/JUCE/extras/Projucer/Builds/MacOSX
          # xcodebuild -project Projucer.xcodeproj -scheme Projucer -configuration Release
          # cp -R build/Release/Projucer.app builds/

      # Add additional steps for testing, packaging, etc. as needed
      # xcodebuild -project Projucer.xcodeproj -scheme Projucer -configuration Release
      # cp -R build/Release/Projucer.app builds/
